FROM walkero/electronbuilderondocker:base

LABEL maintainer="Georgios Sokianos <walkero@gmail.com>"

RUN dpkg --add-architecture i386 && apt-get update && apt-get -y install \
    wine \
    wine32;

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

